stages:
  - build

cmssw_compile:
  stage: build
  only:
    - master
  tags:
    - cvmfs
  variables:
    CMS_PATH: /cvmfs/cms.cern.ch
    CMSSW_RELEASE: CMSSW_10_2_21
  script:
     - /bin/bash ./.gitlab/build.sh